CC ?= gcc
CFLAGS_BENCH ?= -std=gnu99 -O3
LFLAGS_BENCH ?= -lpng $(LDFLAGS)
CFLAGS_CONV ?= -std=c99 -O3
LFLAGS_CONV ?= $(LDFLAGS)

TARGET_BENCH ?= qoibench
TARGET_CONV ?= qoiconv
TARGET_BENCH_ROI ?= roibench
TARGET_CONV_ROI ?= roiconv

all: $(TARGET_BENCH) $(TARGET_CONV) $(TARGET_BENCH_ROI) $(TARGET_CONV_ROI)

bench: $(TARGET_BENCH)
$(TARGET_BENCH):$(TARGET_BENCH).c qoi.h
	$(CC) $(CFLAGS_BENCH) $(CFLAGS) $(TARGET_BENCH).c -o $(TARGET_BENCH) $(LFLAGS_BENCH)

conv: $(TARGET_CONV)
$(TARGET_CONV):$(TARGET_CONV).c qoi.h
	$(CC) $(CFLAGS_CONV) $(CFLAGS) $(TARGET_CONV).c -o $(TARGET_CONV) $(LFLAGS_CONV)


bench-roi: $(TARGET_BENCH_ROI)
$(TARGET_BENCH_ROI):$(TARGET_BENCH).c roi.h
	$(CC) -DROI $(CFLAGS_BENCH) $(CFLAGS) $(TARGET_BENCH).c -o $(TARGET_BENCH_ROI) $(LFLAGS_BENCH)

conv-roi: $(TARGET_CONV_ROI)
$(TARGET_CONV_ROI):$(TARGET_CONV).c roi.h
	$(CC) -DROI $(CFLAGS_CONV) $(CFLAGS) $(TARGET_CONV).c -o $(TARGET_CONV_ROI) $(LFLAGS_CONV)

.PHONY: clean
clean:
	$(RM) $(TARGET_BENCH) $(TARGET_CONV)
